// AppView.swift
// PodWang — a native macOS podcast client.
//
// View hierarchy:
//   AppView
//   ├── SetupView            — first-run folder selection screen
//   └── NavigationSplitView
//       ├── SidebarView      — feed list (SidebarView.swift)
//       └── EpisodeDetailView
//           ├── EpisodeRowView       — one row per episode
//           ├── DownloadButtonView   — idle / downloading / downloaded states
//           ├── ShowNotesPopover     — scrollable HTML-cleaned show notes
//           └── PlayerBarView        — persistent playback controls

import SwiftUI
import UniformTypeIdentifiers

// MARK: - App View

/// Root view. Switches between SetupView (no folder chosen) and the main
/// NavigationSplitView once a downloads folder has been configured.
struct AppView: View {
    @StateObject var manager = PodWangManager()
    @State private var selectedFeed: Feed?
    @State private var searchText = ""

    @State private var showingFilePicker   = false
    @State private var showingFileExporter = false
    @State private var opmlDoc: OPMLDocument?

    var body: some View {
        Group {
            if manager.isStorageConfigured {
                NavigationSplitView {
                    SidebarView(
                        manager: manager,
                        selectedFeed: $selectedFeed,
                        searchText: $searchText,
                        showingFilePicker: $showingFilePicker,
                        showingFileExporter: $showingFileExporter,
                        opmlDoc: $opmlDoc
                    )
                    .searchable(text: $searchText, placement: .sidebar, prompt: "Search Feeds")
                } detail: {
                    if let feed = selectedFeed {
                        EpisodeDetailView(manager: manager, feed: feed)
                    } else {
                        EmptyDetailView()
                    }
                }
                .navigationTitle(selectedFeed?.title ?? "PodWang")
            } else {
                SetupView(manager: manager)
            }
        }
        // File importer for OPML/XML import — presented by the sidebar gear menu.
        .fileImporter(
            isPresented: $showingFilePicker,
            allowedContentTypes: [.xml],
            allowsMultipleSelection: false
        ) { result in
            if let url = try? result.get().first { manager.importFromOPML(url: url) }
        }
        // File exporter for OPML/XML export — document is generated by the sidebar gear menu.
        .fileExporter(
            isPresented: $showingFileExporter,
            document: opmlDoc,
            contentType: .xml,
            defaultFilename: "PodWang Backup"
        ) { _ in }
    }
}

// MARK: - Setup View

/// Shown on first launch. Prompts the user to choose a parent folder for downloads.
/// Required for sandboxed file access via security-scoped bookmarks.
private struct SetupView: View {
    let manager: PodWangManager

    var body: some View {
        VStack(spacing: 24) {
            Image(systemName: "folder.badge.plus")
                .font(.system(size: 80))
                .foregroundColor(.accentColor)

            VStack(spacing: 8) {
                Text("Setup Storage Location").font(.largeTitle).bold()
                Text("Select a folder for PodWang to keep your podcasts organized.")
                    .foregroundColor(.secondary)
            }

            Button { manager.selectDownloadsFolder() } label: {
                Text("Choose Parent Folder…").frame(width: 220)
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.large)
        }
        .frame(minWidth: 700, minHeight: 500)
    }
}

// MARK: - Empty Detail View

/// Placeholder shown when no feed is selected. The app icon is used as a subtle
/// blurred background for visual continuity with the episode detail view.
private struct EmptyDetailView: View {
    var body: some View {
        ZStack {
            if let appIcon = NSApp.applicationIconImage {
                Image(nsImage: appIcon)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .padding(100)
                    .opacity(0.1)
                    .blur(radius: 5)
            }
            VStack(spacing: 16) {
                Image(systemName: "antenna.radiowaves.left.and.right")
                    .font(.system(size: 48))
                    .foregroundColor(.secondary)
                Text("Select a Podcast")
                    .font(.title2)
                    .foregroundColor(.secondary)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

// MARK: - Episode Detail View

/// Shows the episode list for a selected feed, overlaid on a blurred artwork background.
/// Includes toolbar controls for sorting and bulk download, plus the player bar at the bottom.
struct EpisodeDetailView: View {
    @ObservedObject var manager: PodWangManager
    let feed: Feed
    @State private var showingDownloadAllAlert = false
    @State private var episodeSearchText = ""

    /// Episodes filtered by the current search text.
    /// Returns all sorted episodes when the search field is empty.
    private var filteredEpisodes: [Episode] {
        guard !episodeSearchText.isEmpty else { return manager.sortedEpisodes }
        return manager.sortedEpisodes.filter {
            $0.title.localizedCaseInsensitiveContains(episodeSearchText)
        }
    }

    var body: some View {
        ZStack {
            // Blurred feed artwork shown subtly behind the episode list.
            // Falls back to the app icon if no artwork URL is available.
            if let imageURL = manager.currentFeedImageURL, let url = URL(string: imageURL) {
                AsyncImage(url: url) { phase in
                    switch phase {
                    case .success(let image):
                        image.resizable().aspectRatio(contentMode: .fit)
                            .padding(100).opacity(0.1).blur(radius: 5)
                    case .failure:
                        appIconBackground
                    case .empty:
                        ProgressView().opacity(0.2)
                    @unknown default:
                        EmptyView()
                    }
                }
                .id(imageURL) // Forces a refresh when switching between podcasts.
            } else {
                appIconBackground
            }

            VStack(spacing: 0) {
                if manager.isFetching {
                    Spacer()
                    ProgressView("Fetching Episodes…")
                    Spacer()
                } else {
                    List(filteredEpisodes) { episode in
                        EpisodeRowView(manager: manager, episode: episode, feedTitle: feed.title)
                    }
                    .searchable(text: $episodeSearchText, placement: .toolbar, prompt: "Search Episodes")
                    .scrollContentBackground(.hidden) // Lets the artwork background show through.
                    .toolbar {
                        ToolbarItem(placement: .primaryAction) {
                            Button { showingDownloadAllAlert = true } label: {
                                Text("Download All")
                            }
                            .buttonStyle(.bordered)
                            .disabled(filteredEpisodes.isEmpty)
                        }
                        ToolbarItem(placement: .primaryAction) {
                            Button { manager.sortNewestFirst.toggle() } label: {
                                Label("Sort", systemImage: manager.sortNewestFirst ? "arrow.up.circle" : "arrow.down.circle")
                            }
                        }
                    }
                    .alert("Download All Episodes?", isPresented: $showingDownloadAllAlert) {
                        Button("Cancel", role: .cancel) { }
                        Button("Download") {
                            // Respects any active search filter — only downloads visible episodes.
                            for episode in filteredEpisodes where episode.localFileName == nil {
                                manager.download(episode, from: feed.title)
                            }
                        }
                    } message: {
                        Text("This will attempt to download all the displayed episodes for '\(feed.title)'.")
                    }
                }

                PlayerBarView(manager: manager)
            }
        }
        .onAppear { manager.fetchEpisodes(for: feed) }
        .onChange(of: feed) { _, newFeed in manager.fetchEpisodes(for: newFeed) }
    }

    /// Blurred app icon, used as the background when no feed artwork is available.
    private var appIconBackground: some View {
        Group {
            if let appIcon = NSApp.applicationIconImage {
                Image(nsImage: appIcon)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .padding(100)
                    .opacity(0.1)
                    .blur(radius: 5)
            }
        }
    }
}

// MARK: - Duration Formatting

/// Formats a raw `itunes:duration` string into a clean display string.
/// Handles three formats: total seconds ("3661"), mm:ss ("61:01"), hh:mm:ss ("1:01:01").
/// Returns nil if the value is absent or cannot be parsed.
private func formattedDuration(_ raw: String?) -> String? {
    guard let raw = raw, !raw.isEmpty else { return nil }

    // Purely numeric — treat as total seconds and reformat.
    if let totalSeconds = Int(raw) {
        let h = totalSeconds / 3600
        let m = (totalSeconds % 3600) / 60
        let s = totalSeconds % 60
        return h > 0
            ? String(format: "%d:%02d:%02d", h, m, s)
            : String(format: "%d:%02d", m, s)
    }

    // Already in mm:ss or hh:mm:ss — validate and return as-is.
    let parts = raw.split(separator: ":").compactMap { Int($0) }
    guard parts.count >= 2 else { return nil }
    return raw
}

// MARK: - Episode Row View

/// A single row in the episode list showing title, date, duration, and action buttons.
private struct EpisodeRowView: View {
    @ObservedObject var manager: PodWangManager
    let episode: Episode
    let feedTitle: String

    @State private var showingNotes = false

    var body: some View {
        HStack {
            VStack(alignment: .leading, spacing: 4) {
                Text(episode.title).font(.headline).lineLimit(2)
                HStack(spacing: 8) {
                    if let date = episode.pubDate {
                        Text(date.formatted(date: .abbreviated, time: .omitted))
                            .font(.caption).foregroundColor(.secondary)
                    }
                    if let duration = formattedDuration(episode.duration) {
                        if episode.pubDate != nil {
                            Text("·").font(.caption).foregroundColor(.secondary)
                        }
                        Text(duration).font(.caption).foregroundColor(.secondary)
                    }
                }
            }

            Spacer()

            DownloadButtonView(manager: manager, episode: episode, feedTitle: feedTitle)
                .padding(.trailing, 8)

            let isCurrentAndPlaying = manager.currentPlayingEpisode?.id == episode.id && manager.isPlaying
            Button { manager.play(episode) } label: {
                Image(systemName: isCurrentAndPlaying ? "pause.circle" : "play.circle")
                    .font(.title)
            }
            .buttonStyle(.plain)
            .foregroundColor(.accentColor)

            // Info button — only shown when show notes are available.
            if !episode.description.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                Button { showingNotes = true } label: {
                    Image(systemName: "info.circle")
                        .font(.title)
                        .foregroundColor(.accentColor)
                }
                .buttonStyle(.plain)
                .help("Show notes")
                .popover(isPresented: $showingNotes, arrowEdge: .trailing) {
                    ShowNotesPopover(episode: episode)
                }
            }
        }
        .padding(.vertical, 4)
    }
}

// MARK: - Download Button View

/// Renders one of three download states for an episode, all sized to match the play button:
///   1. Downloaded  — folder icon (accent colour); tapping reveals the file in Finder
///   2. Downloading — circular progress ring with percentage label, plus a cancel button
///   3. Idle        — download arrow (accent colour)
private struct DownloadButtonView: View {
    @ObservedObject var manager: PodWangManager
    let episode: Episode
    let feedTitle: String

    var body: some View {
        if let relativePath = episode.localFileName {
            // State 1: file is on disk.
            Button {
                let url = manager.effectiveDownloadsURL().appendingPathComponent(relativePath)
                NSWorkspace.shared.activateFileViewerSelecting([url])
            } label: {
                Image(systemName: "folder")
                    .font(.title)
                    .foregroundColor(.accentColor)
            }
            .buttonStyle(.plain)
            .help("Show in Finder")

        } else if let progress = manager.downloadProgress[episode.id] {
            // State 2: download in progress.
            HStack(spacing: 8) {
                ZStack {
                    Circle()
                        .stroke(Color.secondary.opacity(0.25), lineWidth: 2.5)
                    Circle()
                        .trim(from: 0, to: progress.fractionCompleted)
                        .stroke(Color.accentColor, style: StrokeStyle(lineWidth: 2.5, lineCap: .round))
                        .rotationEffect(.degrees(-90))           // Start from 12 o'clock.
                        .animation(.linear(duration: 0.2), value: progress.fractionCompleted)
                    Text("\(Int(progress.fractionCompleted * 100))%")
                        .font(.system(size: 7, weight: .medium))
                        .foregroundColor(.secondary)
                }
                .frame(width: 28, height: 28)

                Button { manager.cancelDownload(for: episode) } label: {
                    Image(systemName: "xmark.circle")
                        .font(.title)
                        .foregroundColor(.secondary)
                }
                .buttonStyle(.plain)
                .help("Cancel download")
            }

        } else {
            // State 3: not yet downloaded.
            Button { manager.download(episode, from: feedTitle) } label: {
                Image(systemName: "arrow.down.circle")
                    .font(.title)
                    .foregroundColor(.accentColor)
            }
            .buttonStyle(.plain)
            .help("Download episode")
        }
    }
}

// MARK: - Player Bar View

/// Persistent playback bar shown at the bottom of the detail view whenever an episode
/// is loaded. Contains the episode title, a scrubber with time labels, and transport controls.
struct PlayerBarView: View {
    @ObservedObject var manager: PodWangManager

    var body: some View {
        if let playing = manager.currentPlayingEpisode {
            VStack(spacing: 0) {
                Divider()
                VStack(spacing: 8) {

                    // Episode title and stop button.
                    HStack {
                        Text(playing.title)
                            .font(.caption).bold().lineLimit(1).foregroundColor(.secondary)
                        Spacer()
                        Button { manager.stop() } label: {
                            Image(systemName: "xmark.circle.fill")
                        }
                        .buttonStyle(.plain)
                        .help("Stop playback")
                    }
                    .padding([.horizontal, .top])

                    // Scrubber and elapsed/remaining time labels.
                    VStack(spacing: 4) {
                        Slider(
                            value: Binding(get: { manager.currentTime }, set: { manager.seek(to: $0) }),
                            in: 0...max(1, manager.duration)
                        )
                        .controlSize(.small)

                        HStack {
                            Text(manager.currentTime.formattedAsPlaybackTime)
                            Spacer()
                            Text(manager.duration.formattedAsPlaybackTime)
                        }
                        .font(.caption2).foregroundColor(.secondary)
                    }
                    .padding(.horizontal)

                    // Transport controls: ⏮60s ⏮30s ▶/⏸ ⏭30s ⏭60s
                    HStack(spacing: 25) {
                        Button { manager.skip(seconds: -60) } label: { Image(systemName: "gobackward.60").font(.title3) }
                        Button { manager.skip(seconds: -30) } label: { Image(systemName: "gobackward.30").font(.title3) }
                        Button { manager.play(playing) } label: {
                            Image(systemName: manager.isPlaying ? "pause.fill" : "play.fill")
                                .font(.title).frame(width: 40)
                        }
                        Button { manager.skip(seconds: 30) } label: { Image(systemName: "goforward.30").font(.title3) }
                        Button { manager.skip(seconds: 60) } label: { Image(systemName: "goforward.60").font(.title3) }
                    }
                    .buttonStyle(.plain)
                    .padding(.bottom, 15)
                }
                .background(.ultraThinMaterial)
            }
        }
    }
}

// MARK: - Show Notes Popover

/// Displays the episode description as scrollable plain text.
///
/// RSS show notes are typically HTML. `cleanedNotes` strips tags with a regex and
/// decodes common HTML entities to produce readable plain text, without the overhead
/// of a full WKWebView. Formatting quirks from feed producers may still appear.
private struct ShowNotesPopover: View {
    let episode: Episode

    private var cleanedNotes: String {
        var text = episode.description

        // Strip HTML tags.
        text = text.replacingOccurrences(of: "<[^>]+>", with: " ", options: .regularExpression)

        // Decode common HTML entities.
        let entities: [(String, String)] = [
            ("&amp;",   "&"),
            ("&lt;",    "<"),
            ("&gt;",    ">"),
            ("&quot;",  "\""),
            ("&#39;",   "'"),
            ("&nbsp;",  " "),
            ("&mdash;", "—"),
            ("&ndash;", "–"),
            ("&lsquo;", "'"),
            ("&rsquo;", "'"),
            ("&ldquo;", "\u{201C}"),
            ("&rdquo;", "\u{201D}"),
        ]
        for (entity, replacement) in entities {
            text = text.replacingOccurrences(of: entity, with: replacement)
        }

        // Collapse whitespace and blank lines into clean paragraphs.
        text = text.components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n")

        return text.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(episode.title)
                .font(.headline)
                .lineLimit(3)

            Divider()

            ScrollView {
                Text(cleanedNotes.isEmpty ? "No show notes available." : cleanedNotes)
                    .font(.body)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .textSelection(.enabled)
            }
        }
        .padding()
        .frame(width: 380, height: 320)
    }
}
